import type { CreateEventInput, UpdateEventInput } from "@unveiled/db";

import type { EventFormValues } from "./admin-event-form";
import { eventFormValuesToOccurrenceLists } from "./admin-event-form";

export function toCreateEventInput(values: EventFormValues, uploadedBy: string): CreateEventInput {
  const { dateTimes, occurrenceCreditPrices } = eventFormValuesToOccurrenceLists(values);
  return {
    partnerId: values.partnerId,
    title: values.title,
    description: values.description,
    street: values.street,
    houseNumber: values.houseNumber,
    addressLine2: values.addressLine2,
    zipCode: values.zipCode,
    country: values.country,
    city: values.city,
    category: values.category,
    eventType: values.eventType,
    tags: values.tags,
    dateTimes,
    occurrenceCreditPrices,
    timingMode: values.timingMode,
    creditPrice: values.creditPrice,
    totalCapacity: values.totalCapacity,
    ticketType: values.ticketType,
    secretCode: values.secretCode,
    eventWebsiteUrl: values.eventWebsiteUrl,
    barrierFree: values.barrierFree,
    languageIndependent: values.languageIndependent,
    languages: values.languages,
    hasSubtitles: values.hasSubtitles,
    subtitleLanguage: values.subtitleLanguage,
    lat: values.lat,
    lng: values.lng,
    imageUpload: values.imageUpload,
    imageUrl: values.imageUrl,
    imagePrebuilt: values.imagePrebuilt,
    stagedImageId: values.stagedImageId,
    uploadedBy,
  };
}

export function toUpdateEventInput(values: EventFormValues, uploadedBy: string): UpdateEventInput {
  const { dateTimes, occurrenceCreditPrices } = eventFormValuesToOccurrenceLists(values);
  return {
    partnerId: values.partnerId,
    title: values.title,
    description: values.description,
    street: values.street,
    houseNumber: values.houseNumber,
    addressLine2: values.addressLine2,
    zipCode: values.zipCode,
    country: values.country,
    city: values.city,
    category: values.category,
    eventType: values.eventType,
    tags: values.tags,
    dateTimes,
    occurrenceCreditPrices,
    timingMode: values.timingMode,
    creditPrice: values.creditPrice,
    totalCapacity: values.totalCapacity,
    ticketType: values.ticketType,
    secretCode: values.secretCode,
    eventWebsiteUrl: values.eventWebsiteUrl,
    barrierFree: values.barrierFree,
    languageIndependent: values.languageIndependent,
    languages: values.languages,
    hasSubtitles: values.hasSubtitles,
    subtitleLanguage: values.subtitleLanguage,
    lat: values.lat,
    lng: values.lng,
    imageUpload: values.imageUpload,
    imageUrl: values.imageUrl,
    imagePrebuilt: values.imagePrebuilt,
    stagedImageId: values.stagedImageId,
    uploadedBy,
  };
}

export function toSeriesCreateInput(
  values: EventFormValues,
  slots: Date[],
  uploadedBy: string,
): Omit<CreateEventInput, "dateTimes"> & { slots: Date[] } {
  // Series forms omit datetime rows — do not call eventFormValuesToDateTimes.
  return {
    partnerId: values.partnerId,
    title: values.title,
    description: values.description,
    street: values.street,
    houseNumber: values.houseNumber,
    addressLine2: values.addressLine2,
    zipCode: values.zipCode,
    country: values.country,
    city: values.city,
    category: values.category,
    eventType: values.eventType,
    tags: values.tags,
    timingMode: values.timingMode,
    creditPrice: values.creditPrice,
    totalCapacity: values.totalCapacity,
    ticketType: values.ticketType,
    secretCode: values.secretCode,
    eventWebsiteUrl: values.eventWebsiteUrl,
    barrierFree: values.barrierFree,
    languageIndependent: values.languageIndependent,
    languages: values.languages,
    hasSubtitles: values.hasSubtitles,
    subtitleLanguage: values.subtitleLanguage,
    lat: values.lat,
    lng: values.lng,
    imageUpload: values.imageUpload,
    imageUrl: values.imageUrl,
    imagePrebuilt: values.imagePrebuilt,
    stagedImageId: values.stagedImageId,
    uploadedBy,
    slots,
  };
}
