export type CatalogErrorCode =
  | "ALREADY_FEATURED"
  | "CLIENT_IMAGE_REQUIRED"
  | "CONFLICTING_IMAGE_SOURCES"
  | "DUPLICATE_OCCURRENCE_INSTANTS"
  | "DUPLICATE_SERIES_SLOTS"
  | "DUPLICATE_VOUCHER_CODE"
  | "EMPTY_DATE_TIMES"
  | "EMPTY_SERIES_SLOTS"
  | "EMPTY_VOUCHER_INVENTORY"
  | "EVENT_NOT_FOUND"
  | "FEATURED_PARTNERS_REORDER_INVALID"
  | "GALLERY_DUPLICATE_IMAGE"
  | "GALLERY_REORDER_INVALID"
  | "IMAGE_CREDIT_TOO_LONG"
  | "IMAGE_NOT_FOUND"
  | "INVALID_EMAIL"
  | "INVALID_OPENING_HOURS"
  | "INVALID_REDEMPTION_CONFIG"
  | "INVALID_SUBTITLE_LANGUAGE"
  | "MISSING_EVENT_IMAGE"
  | "NEGATIVE_CREDIT_PRICE"
  | "OCCURRENCE_LENGTH_MISMATCH"
  | "PARTNER_HAS_EVENTS"
  | "PARTNER_NOT_FOUND"
  | "REQUIRED_FIELD"
  | "TOO_MANY_OCCURRENCES";

export class CatalogValidationError extends Error {
  readonly code: CatalogErrorCode;

  constructor(code: CatalogErrorCode, message: string) {
    super(message);
    this.name = "CatalogValidationError";
    this.code = code;
  }
}
